name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Files
        run: cd ../link-shortener && ls -la

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # - name: Go to scripts directory
      #   run: cd scripts

      # - name: List current path
      #   run: pwd

      # - name: List Files
      #   run: ls -la

      - name: Build in Release Mode
        run: cd && cargo build --release

      - name: Read Project Version
        run: |
          echo "::set-output name=version::$(grep version scripts/Cargo.toml | head -n 1 | awk '{print $3}')"

      - name: Copy Binary to Release Folder
        run: cp scripts/target/release/scripts scripts/release/scripts-${{ steps.read_project_version.outputs.version }}
